comment_width = 120
format_code_in_doc_comments = true
format_strings = true
max_width = 120
merge_derives = true
merge_imports = true
normalize_comments = true
unstable_features = true
wrap_comments = true
